<footer>
  <div class="container">
    <p>&copy; 2025 TechHive. All rights reserved.</p>
    <address>
      Contact us at: <a href="mailto:info@techhive.com">info@techhive.com</a>
    </address>
    <p>
      <a href="https://github.com/tat2912/COS10026-Project-Part-1"
        target="_blank" rel="noopener">GitHub Repository</a>
      |
      <a href="https://skr1ptk1dd13.atlassian.net/jira/software/projects/AC/boards/34"
        target="_blank" rel="noopener">Jira Project</a>
    </p>
  </div>
</footer>
